#!/bin/bash
# sflow-rt    Real-time sFlow analyzer
#
# chkconfig: 345 90 20
# description: Receives sFlow and presents REST API
# pidfile: /var/run/sflow-rt.pid 

NAME="sFlow-RT"
START=/etc/sflow-rt/start.sh
PIDFILE=/var/run/sflow-rt.pid

start() {
  echo -n "Starting $NAME: "
  if  [ -f $PIDFILE ]; then
     PID=`cat $PIDFILE`
     echo Already running: $PID
     exit 2;
  else
     nohup $START < /dev/null > /dev/null 2>&1 &
     RETVAL=$!
     echo Started PID: $RETVAL
     echo $RETVAL >>$PIDFILE
     return $RETVAL
  fi
}

status() {
  echo -n "Status $NAME: "
  if [ -f $PIDFILE ]; then
    PID=`cat $PIDFILE`
    echo Running: $PID
  else
    echo Not running
  fi
}

stop() {
  if [ -f $PIDFILE ]; then
    PID=`cat $PIDFILE`
    echo -n "Stopping $NAME "
    echo
    kill $PID
    rm -f $PIDFILE
  else
    echo Not running
  fi
  return 0
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status) 
    status
    ;;
  restart)
    stop
    sleep 2
    start
    ;;
  *)
    echo "Usage: {start|stop|status|restart}"
    exit 1
    ;;
esac
exit $?
